/** Query expansions and intent aliases for concierge-style search. */
export const SEARCH_SYNONYMS: Record<string, string[]> = {
  movie: ["movies", "cinema", "film", "stars"],
  campfire: ["campfires", "marshmallow", "smores", "s'mores", "fire", "bonfire"],
  craft: ["crafts", "arts", "kids", "coloring", "painting"],
  pool: ["poolside", "swim", "swimming"],
  yoga: ["wellness", "fitness", "stretch", "meditation"],
  arcade: ["games", "game"],
  hunt: ["scavenger", "scavenger hunt"],
  music: ["band", "concert", "dj"],
  evening: ["tonight", "night", "after dinner", "starlight"],
  morning: ["breakfast", "early"],
  resort: ["resorts", "hotel", "hotels"],
  plan: ["itinerary", "saved", "my plan"],
  tonight: ["this evening", "after dark"],
  today: ["this afternoon", "right now", "happening now"],
};

export const CATEGORY_QUERY_ALIASES: Record<string, string> = {
  movie: "movies_under_stars",
  movies: "movies_under_stars",
  cinema: "movies_under_stars",
  film: "movies_under_stars",
  campfire: "campfire",
  campfires: "campfire",
  marshmallow: "campfire",
  fire: "campfire",
  pool: "poolside",
  swim: "poolside",
  craft: "arts_crafts",
  crafts: "arts_crafts",
  kids: "arts_crafts",
  yoga: "fitness_wellness",
  wellness: "fitness_wellness",
  fitness: "fitness_wellness",
  arcade: "arcade",
  games: "arcade",
  hunt: "scavenger_hunt",
  scavenger: "scavenger_hunt",
  music: "music",
  evening: "nighttime_entertainment",
  signature: "signature",
  nature: "nature",
};

export const PAGE_HITS = [
  {
    id: "page-tonight",
    title: "Tonight",
    description: "Movies, campfires, and evening resort fun",
    href: "/tonight",
    keywords: ["tonight", "evening", "night", "movies", "campfire", "starlight"],
  },
  {
    id: "page-today",
    title: "Today",
    description: "What's happening at the resorts right now",
    href: "/today",
    keywords: ["today", "now", "happening", "this afternoon"],
  },
  {
    id: "page-calendar",
    title: "Resort calendar",
    description: "Browse source-backed resort activities",
    href: "/activities",
    keywords: ["calendar", "activities", "browse", "resort fun"],
  },
  {
    id: "page-resorts",
    title: "All resorts",
    description: "Browse every Walt Disney World resort hotel",
    href: "/resorts",
    keywords: ["resorts", "resort", "hotel", "hotels", "pick resort"],
  },
  {
    id: "page-plan",
    title: "My plan",
    description: "Save activities and build your daybook",
    href: "/plan",
    keywords: ["plan", "saved", "itinerary", "daybook"],
  },
  {
    id: "page-guides",
    title: "Planning guides",
    description: "First night tips, arcade listings, and resort activities",
    href: "/guides",
    keywords: ["guides", "guide", "tips", "help", "planning"],
  },
  {
    id: "page-explore",
    title: "Explore activities",
    description: "Filter by resort, category, and time of day",
    href: "/activities",
    keywords: ["explore", "activities", "browse", "all activities"],
  },
] as const;
