"""Fort Wilderness curated activities (no official A-frame PDF)."""

from __future__ import annotations

from pdf_parser import ParsedActivity

# Source: https://disneyworld.disney.go.com/resorts/campsites-at-fort-wilderness-resort/recreation/
FORT_WILDERNESS_ACTIVITIES: list[ParsedActivity] = [
    ParsedActivity(
        name="Chip 'N' Dale's Campfire Sing-A-Long",
        normalized_name="chip-n-dales-campfire-sing-a-long",
        category="campfire",
        section="RESORT ACTIVITIES",
        location="Chip's Campfire Sing-A-Long",
        schedule_text="Nightly",
        is_daily=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Fort Wilderness Archery Experience",
        normalized_name="fort-wilderness-archery-experience",
        category="resort_activity",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Tri-Circle-D Ranch Pony Rides",
        normalized_name="tri-circle-d-ranch-pony-rides",
        category="resort_activity",
        section="RESORT ACTIVITIES",
        location="Tri-Circle-D Ranch",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Tri-Circle-D Ranch Wagon Rides",
        normalized_name="tri-circle-d-ranch-wagon-rides",
        category="resort_activity",
        section="RESORT ACTIVITIES",
        location="Tri-Circle-D Ranch",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Horse Drawn Excursion – Carriage Ride",
        normalized_name="horse-drawn-excursion-carriage-ride",
        category="resort_activity",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Holiday Sleigh Rides",
        normalized_name="holiday-sleigh-rides",
        category="resort_activity",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Bike Rentals",
        normalized_name="bike-rentals",
        category="rental",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Canoe Rentals",
        normalized_name="canoe-rentals",
        category="rental",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Kayak Rentals",
        normalized_name="kayak-rentals",
        category="rental",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Movies Under the Stars",
        normalized_name="movies-under-the-stars",
        category="movies_under_stars",
        section="MOVIE UNDER THE STARS",
        confidence=1.0,
    ),
    ParsedActivity(
        name="Wilderness Back Trail Adventure",
        normalized_name="wilderness-back-trail-adventure",
        category="resort_activity",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Davy Crockett's Wilderness Arcade",
        normalized_name="davy-crocketts-wilderness-arcade",
        category="arcade",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Daniel Boone's Wilderness Arcade",
        normalized_name="daniel-boones-wilderness-arcade",
        category="arcade",
        section="RESORT ACTIVITIES",
        is_fee_based=True,
        confidence=1.0,
    ),
    ParsedActivity(
        name="Electrical Water Pageant",
        normalized_name="electrical-water-pageant",
        category="nighttime_entertainment",
        section="RESORT ACTIVITIES",
        description="Viewable from resort waterfront areas.",
        confidence=1.0,
    ),
]
